# .github/workflows/ci.yml
name: CI/CD using github actions and docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB_NAME }}
          MYSQL_USER: ${{ secrets.MYSQL_DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Add swap space
      run: |
        sudo dd if=/dev/zero of=/swapfile bs=1M count=8192
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show
        free -h

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" >> .env
        echo "MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}" >> .env
        echo "MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> .env
        echo "MYSQL_DB_USER=${{ secrets.MYSQL_DB_USER }}" >> .env
        echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> .env
        echo "MAIN_DOMAIN=${{ secrets.MAIN_DOMAIN }}" >> .env
        echo "SOCIAL_AUTH_GOOGLE_CLIENT_ID=${{ secrets.SOCIAL_AUTH_GOOGLE_CLIENT_ID }}" >> .env
        echo "SOCIAL_AUTH_GOOGLE_SECRET=${{ secrets.SOCIAL_AUTH_GOOGLE_SECRET }}" >> .env
        echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> .env
        echo "STATE=${{ secrets.STATE }}" >> .env
        echo "SOCIAL_AUTH_NAVER_CLIENT_ID=${{ secrets.SOCIAL_AUTH_NAVER_CLIENT_ID }}" >> .env
        echo "SOCIAL_AUTH_NAVER_SECRET=${{ secrets.SOCIAL_AUTH_NAVER_SECRET }}" >> .env
        echo "NAVER_CALLBACK_URL=${{ secrets.NAVER_CALLBACK_URL }}" >> .env
        echo "SOCIAL_AUTH_KAKAO_CLIENT_ID=${{ secrets.SOCIAL_AUTH_KAKAO_CLIENT_ID }}" >> .env
        echo "SOCIAL_AUTH_KAKAO_SECRET=${{ secrets.SOCIAL_AUTH_KAKAO_SECRET }}" >> .env
        echo "KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> .env
        echo "AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}" >> .env

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Wait for db to be ready
      run: |
        docker-compose exec -T web /wait-for-it.sh db:3306 -- echo "Database is up"

    - name: Run tests
      run: |
        docker-compose run web python manage.py test

    - name: Stop and remove Docker Compose containers
      run: |
        docker-compose down
