name: Test Secrets

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print Docker Hub Username
      run: |
        echo "Docker Hub Username: ${{ secrets.DOCKER_HUB_USERNAME }}"

    - name: Print Docker Hub Token Length
      run: |
        echo "Docker Hub Token Length: ${#${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}}"

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    
